prep.evi <- function(evi.path, evi.pattern, yr = '2018', timestr,
                     reg.name = NULL, reg.ext) {
  
  evi.files <- list.files(evi.path, evi.pattern, full.names = T)
  
  if (length(evi.files) > 1) {
    evi.file <- evi.files[1]#grepl(yr, evi.files)]
    #if (yr > evi.max.yr) evi.file <- evi.files[length(evi.files)]
  } else evi.file = evi.files  
  
  doy = yday(as.Date(timestr,format = '%Y%m%d%H'))

  # requires shapefile (can be generated by calling create.shapefile())
  # make sure LC domain > your target `reg.ext`
  if (length(evi.file) == 0) {  # if no land cover data found, create shapefile
    create.shapefile(reg.name, reg.ext, outpath = evi.path, overwrite = T) 
    stop(paste('predGPP(): NO EVI data for required region in', yr,
               '\nPlease check created shapefiles under', evi.path, 
               'and download local EVI data (from MODIS)'))
  } else {
    
    if (grepl('nc',  evi.file)) evi.stk <- stack(evi.file, varname = 'MODIS_EVI')
    if (grepl('tif', evi.file)) evi.stk <- raster(evi.file, band=doy)
      #evi.ref <- evi.stk[EVI_index]
    if ( nlayers(evi.stk) > 1 ) {
      evi.names   <- as.numeric(substr(gsub('X', '', names(evi.stk)), 1, 4))
      layer.indx <- findInterval(yr, evi.names)
      evi.rt      <- raster::crop(subset(evi.stk, layer.indx), reg.ext)
    } else evi.rt <- raster::crop(evi.stk, reg.ext)   # end if subset layers
  }   # end if LC file        
  return(evi.rt)#, evi.ref)
}