prep.isa <- function(isa.path, isa.pattern, yr = '2018', isa.max.yr, 
                       reg.name = NULL, reg.ext) {
  
  #isa.path <- 'C:/Users/kitty/Documents/Research/SIF/UrbanVPRM/UrbanVPRM/Impermeable_Surface'
  #isa.pattern <- 'all_aggregated_impervious_63_entire_GTA'
  
  # load all MCD data and find the correct one according to @param yr
  isa.files <- list.files(isa.path, isa.pattern, full.names = T)
  
  if (length(isa.files) > 1) {
    isa.file <- isa.files[grepl(yr, isa.files)]
    if (yr > isa.max.yr) isa.file <- isa.files[length(isa.files)]
  } else isa.file = isa.files  
  
  ## download files from https://lpdaacsvc.cr.usgs.gov/appeears/, which 
  # requires shapefile (can be generated by calling create.shapefile())
  # make sure LC domain > your target `reg.ext`
  if (length(isa.file) == 0) {  # if no land cover data found, create shapefile
    create.shapefile(reg.name, reg.ext, outpath = isa.path, overwrite = T) 
    stop(paste('predGPP(): NO Impervious Surface Area data for required region 
               in', yr, '\nPlease check created shapefiles under', isa.path, 
               'and download local ISA data (For Toronto using the city of 
               Torontos Impermeable Surface product (https://ckan0.cf.opendata.
               inter.prod-toronto.ca/gl/dataset/topographic-mapping-impermeable
               -surface), Canadian Annual Crop Inventory (ACI) (https://www.agr.
               gc.ca/atlas/apps/metrics/index-en.html?appid=aci-iac), and the 
               Southern Ontario Land Resource Information System (SOLRIS) 
               (https://www.arcgis.com/home/item.html?id=0279f65b82314121b5b5ec
               93d76bc6ba))'))
  } else {
    
    if (grepl('nc',  isa.file)) isa.stk <- stack(isa.file, varname = 'ISA')
    if (grepl('tif', isa.file)) isa.stk <- raster(isa.file)
    
    if ( nlayers(isa.stk) > 1 ) {
      isa.names   <- as.numeric(substr(gsub('X', '', names(isa.stk)), 1, 4))
      layer.indx <- findInterval(yr, isa.names)
      isa.rt      <- raster::crop(subset(isa.stk, layer.indx), reg.ext)
    } else isa.rt <- raster::crop(isa.stk, reg.ext)   # end if subset layers
  }   # end if LC file        
  return(isa.rt)
}